package agentsdk

import "github.com/gratefulagents/sdk/internal/agent"

type Agent = agent.Agent
type AgentMeta = agent.AgentMeta
type AgentError = agent.AgentError
type AgentHooks = agent.AgentHooks
type AgentLogger = agent.AgentLogger
type AgentOption = agent.AgentOption
type AgentSpanData = agent.AgentSpanData
type CompactionConfig = agent.CompactionConfig
type CompactionData = agent.CompactionData
type CompactionResult = agent.CompactionResult
type CompactionSpanData = agent.CompactionSpanData
type ContentEvent = agent.ContentEvent
type ContextCompactor = agent.ContextCompactor
type EventStream = agent.EventStream
type EventWriter = agent.EventStream
type FunctionTool = agent.FunctionTool
type FunctionSpanData = agent.FunctionSpanData
type GenerationSpanData = agent.GenerationSpanData
type GuardrailResult = agent.GuardrailResult
type GuardrailSpanData = agent.GuardrailSpanData
type Handoff = agent.Handoff
type HandoffCallData = agent.HandoffCallData
type HandoffHistoryConfig = agent.HandoffHistoryConfig
type HandoffOption = agent.HandoffOption
type AsToolOption = agent.AsToolOption
type HandoffOutputData = agent.HandoffOutputData
type HandoffSpanData = agent.HandoffSpanData
type ImmediateInputPoller = agent.ImmediateInputPoller
type InputGuardrail = agent.InputGuardrail
type InputGuardrailTripwireTriggered = agent.InputGuardrailTripwireTriggered
type InputGuardrailResult = agent.InputGuardrailResult
type Interruption = agent.Interruption
type LLMCompaction = agent.LLMCompaction
type LLMOutputSchema = agent.LLMOutputSchema
type LLMReasoning = agent.LLMReasoning
type LLMRequestSnapshot = agent.LLMRequestSnapshot
type LLMResponseSnapshot = agent.LLMResponseSnapshot
type LLMRunItemSnapshot = agent.LLMRunItemSnapshot
type LLMToolApproval = agent.LLMToolApproval
type LLMToolCall = agent.LLMToolCall
type LLMToolSnapshot = agent.LLMToolSnapshot
type LogLevel = agent.LogLevel
type MaxTurnsExceeded = agent.MaxTurnsExceeded
type MessageOutput = agent.MessageOutput
type ImageAttachment = agent.ImageAttachment
type ModeModelRouting = agent.ModeModelRouting
type ModeReasoningLevel = agent.ModeReasoningLevel
type ModeRoleModelRouting = agent.ModeRoleModelRouting
type ModeRoutingResolution = agent.ModeRoutingResolution
type ModeTextVerbosity = agent.ModeTextVerbosity
type Model = agent.Model
type ModelBehaviorError = agent.ModelBehaviorError
type ModelIdentity = agent.ModelIdentity
type ModelProvider = agent.ModelProvider
type ModelRequest = agent.ModelRequest
type ModelResponse = agent.ModelResponse
type ModelRetryAdvice = agent.ModelRetryAdvice
type ModelSettings = agent.ModelSettings
type ModelStream = agent.ModelStream
type ModelStreamEvent = agent.ModelStreamEvent
type ModelStreamEventType = agent.ModelStreamEventType
type ModelUsageEntry = agent.ModelUsageEntry
type MultiProvider = agent.MultiProvider
type MultiTracingProcessor = agent.MultiTracingProcessor
type NestedRunConfig = agent.NestedRunConfig
type NoOpAgentHooks = agent.NoOpAgentHooks
type NoOpRunHooks = agent.NoOpRunHooks
type NoOpTracingProcessor = agent.NoOpTracingProcessor
type OutputGuardrail = agent.OutputGuardrail
type OutputGuardrailTripwireTriggered = agent.OutputGuardrailTripwireTriggered
type OutputGuardrailResult = agent.OutputGuardrailResult
type OutputSchema = agent.OutputSchema
type PlatformHooks = agent.PlatformHooks
type ProgressEvent = agent.ProgressEvent
type ProgressSnapshot = agent.ProgressSnapshot
type ProgressTracker = agent.ProgressTracker
type RunProgress = agent.ProgressTracker
type ReasoningData = agent.ReasoningData
type RetryBackoffSettings = agent.RetryBackoffSettings
type RetryPolicy = agent.RetryPolicy
type RetrySpanData = agent.RetrySpanData
type RunConfig = agent.RunConfig
type RunContext = agent.RunContext
type RunErrorAction = agent.RunErrorAction
type RunErrorData = agent.RunErrorData
type RunErrorDetails = agent.RunErrorDetails
type RunErrorHandler = agent.RunErrorHandler
type RunErrorHandlerResult = agent.RunErrorHandlerResult
type RunHooks = agent.RunHooks
type RunItem = agent.RunItem
type RunItemType = agent.RunItemType
type RunResult = agent.RunResult
type RunState = agent.RunState
type Runner = agent.Runner
type SessionSpanData = agent.SessionSpanData
type SessionMode = agent.SessionMode
type Span = agent.Span
type SpanData = agent.SpanData
type StopAtTools = agent.StopAtTools
type StreamEvent = agent.StreamEvent
type StreamEventType = agent.StreamEventType
type StreamedRunResult = agent.StreamedRunResult
type SubAgentActivityLedger = agent.SubAgentActivity
type SubAgentActivity = agent.SubAgentActivity
type SubAgentActivityEntry = agent.SubAgentActivityEntry
type SubAgentActivitySnapshot = agent.SubAgentActivitySnapshot
type SubAgentDependencyPolicy = agent.SubAgentDependencyPolicy
type SubAgentRegistry = agent.SubAgentRegistry
type SubAgentRegistryConfig = agent.SubAgentRegistryConfig
type SubAgentScheduler = agent.SubAgentRegistry
type SubAgentSpawnOptions = agent.SubAgentSpawnOptions
type SubAgentStreamEvent = agent.SubAgentStreamEvent
type SubAgentTask = agent.SubAgentTask
type SubAgentTaskStatus = agent.SubAgentTaskStatus
type SubagentSpanData = agent.SubagentSpanData
type Tool = agent.Tool
type ToolCallData = agent.ToolCallData
type ToolAccessLevel = agent.ToolAccessLevel
type ToolAccessAdapter = agent.ToolAccessAdapter
type ToolOutputData = agent.ToolOutputData
type ToolApprovalData = agent.ToolApprovalData
type ToolGuardrailResult = agent.ToolGuardrailResult
type ToolInputGuardrail = agent.ToolInputGuardrail
type ToolInputGuardrailTripwireTriggered = agent.ToolInputGuardrailTripwireTriggered
type ToolOutputGuardrail = agent.ToolOutputGuardrail
type ToolOutputGuardrailTripwireTriggered = agent.ToolOutputGuardrailTripwireTriggered
type ToolPolicy = agent.ToolPolicy
type ToolResult = agent.ToolResult
type ToolTimeoutError = agent.ToolTimeoutError
type ToolUseBehavior = agent.ToolUseBehavior
type ToolsToFinalOutputResult = agent.ToolsToFinalOutputResult
type Trace = agent.Trace
type TracingProcessor = agent.TracingProcessor
type TrackerOption = agent.TrackerOption
type Usage = agent.Usage
type UserError = agent.UserError

const (
	DefaultMaxTurns                = agent.DefaultMaxTurns
	DefaultMaxToolResultBytes      = agent.DefaultMaxToolResultBytes
	DefaultSubAgentMaxTurns        = agent.DefaultSubAgentMaxTurns
	RecommendedHandoffPromptPrefix = agent.RecommendedHandoffPromptPrefix

	ModelStreamDelta    = agent.ModelStreamDelta
	ModelStreamItemDone = agent.ModelStreamItemDone
	ModelStreamComplete = agent.ModelStreamComplete
	ModelStreamError    = agent.ModelStreamError

	StreamEventRawResponse  = agent.StreamEventRawResponse
	StreamEventRunItem      = agent.StreamEventRunItem
	StreamEventAgentUpdated = agent.StreamEventAgentUpdated
	StreamEventContent      = agent.StreamEventContent
	StreamEventSubAgent     = agent.StreamEventSubAgent

	RunItemMessage       = agent.RunItemMessage
	RunItemToolCall      = agent.RunItemToolCall
	RunItemToolOutput    = agent.RunItemToolOutput
	RunItemHandoffCall   = agent.RunItemHandoffCall
	RunItemHandoffOutput = agent.RunItemHandoffOutput
	RunItemReasoning     = agent.RunItemReasoning
	RunItemToolApproval  = agent.RunItemToolApproval
	RunItemCompaction    = agent.RunItemCompaction

	RunLLMAgain     = agent.RunLLMAgain
	StopOnFirstTool = agent.StopOnFirstTool

	SessionModeChat = agent.SessionModeChat
	SessionModePlan = agent.SessionModePlan

	ToolAccessLevelFull     = agent.ToolAccessLevelFull
	ToolAccessLevelReadOnly = agent.ToolAccessLevelReadOnly

	ErrorActionRetry    = agent.ErrorActionRetry
	ErrorActionAbort    = agent.ErrorActionAbort
	ErrorActionContinue = agent.ErrorActionContinue

	ReasoningNone   = agent.ReasoningNone
	ReasoningLow    = agent.ReasoningLow
	ReasoningMedium = agent.ReasoningMedium
	ReasoningHigh   = agent.ReasoningHigh
	ReasoningXHigh  = agent.ReasoningXHigh

	TextVerbosityLow    = agent.TextVerbosityLow
	TextVerbosityMedium = agent.TextVerbosityMedium
	TextVerbosityHigh   = agent.TextVerbosityHigh

	LogLevelNormal = agent.LogLevelNormal
	LogLevelDebug  = agent.LogLevelDebug

	SubAgentTaskPending   = agent.SubAgentTaskPending
	SubAgentTaskWaiting   = agent.SubAgentTaskWaiting
	SubAgentTaskRunning   = agent.SubAgentTaskRunning
	SubAgentTaskCompleted = agent.SubAgentTaskCompleted
	SubAgentTaskFailed    = agent.SubAgentTaskFailed
	SubAgentTaskCancelled = agent.SubAgentTaskCancelled

	SubAgentDependencyAllSuccess  = agent.SubAgentDependencyAllSuccess
	SubAgentDependencyAllTerminal = agent.SubAgentDependencyAllTerminal
)

var (
	BuildLLMRequestSnapshot             = agent.BuildLLMRequestSnapshot
	BuildLLMResponseSnapshot            = agent.BuildLLMResponseSnapshot
	BuildRunBudgetContext               = agent.BuildRunBudgetContext
	BuildSubAgentBudgetContext          = agent.BuildSubAgentBudgetContext
	BuildSubAgentDependencyContext      = agent.BuildSubAgentDependencyContext
	BuildSubAgentMonitorContext         = agent.BuildSubAgentMonitorContext
	BuildSubAgentResultsContext         = agent.BuildSubAgentResultsContext
	BuildWorkspaceContext               = agent.BuildWorkspaceContext
	DefaultCompactionConfig             = agent.DefaultCompactionConfig
	DefaultRetryPolicy                  = agent.DefaultRetryPolicy
	CompactionDefaultsForModel          = agent.CompactionDefaultsForModel
	ExtractAgentMeta                    = agent.ExtractAgentMeta
	ExtractAskUserQuestion              = agent.ExtractAskUserQuestion
	ExtractBashCommand                  = agent.ExtractBashCommand
	ExtractCompactionSummary            = agent.ExtractCompactionSummary
	ExtractFilePath                     = agent.ExtractFilePath
	ExtractGlobPattern                  = agent.ExtractGlobPattern
	ExtractGrepPattern                  = agent.ExtractGrepPattern
	ExtractLSPOperation                 = agent.ExtractLSPOperation
	NestedRunConfigFromContext          = agent.NestedRunConfigFromContext
	NewChildEventStream                 = agent.NewChildEventStream
	NewChildTracker                     = agent.NewChildTracker
	NewAgentLogger                      = agent.NewAgentLogger
	NewEventStream                      = agent.NewEventStream
	NewEventWriter                      = agent.NewEventStream
	NewEventHooks                       = agent.NewPlatformHooks
	NewHandoff                          = agent.NewHandoff
	NewModelStream                      = agent.NewModelStream
	NewMultiProvider                    = agent.NewMultiProvider
	NewOutputSchema                     = agent.NewOutputSchema
	NewPlatformHooks                    = agent.NewPlatformHooks
	NewProgressTracker                  = agent.NewProgressTracker
	NewRunProgress                      = agent.NewProgressTracker
	NewRunnerWithModel                  = agent.NewRunnerWithModel
	NewRunnerWithProvider               = agent.NewRunnerWithProvider
	NewSpan                             = agent.NewSpan
	NewSubAgentActivity                 = agent.NewSubAgentActivity
	NewSubAgentRegistry                 = agent.NewSubAgentRegistry
	NewTrace                            = agent.NewTrace
	NormalizeToolAccessLevel            = agent.NormalizeToolAccessLevel
	NormalizeSubAgentDependencyPolicy   = agent.NormalizeSubAgentDependencyPolicy
	NormalizeModelIdentity              = agent.NormalizeModelIdentity
	NormalizeSessionMode                = agent.NormalizeSessionMode
	ParentCallIDFromContext             = agent.ParentCallIDFromContext
	SubAgentStreamEventFromContentEvent = agent.SubAgentStreamEventFromContentEvent
	ModeReasoningSettings               = agent.ModeReasoningSettings
	ModeRoutingSettings                 = agent.ModeRoutingSettings
	ModeTextVerbositySettings           = agent.ModeTextVerbositySettings
	MaybeCompactHandoffInput            = agent.MaybeCompactHandoffInput
	MaybeCompactRunItems                = agent.MaybeCompactRunItems
	MaybeCompactRunItemsForRequest      = agent.MaybeCompactRunItemsForRequest
	ParseModelPrefix                    = agent.ParseModelPrefix
	ResolveModelForProvider             = agent.ResolveModelForProvider
	ResolveModeRouting                  = agent.ResolveModeRouting
	ResolveRoleModeRouting              = agent.ResolveRoleModeRouting
	SnapshotRunItems                    = agent.SnapshotRunItems
	SnapshotTools                       = agent.SnapshotTools
	SpanParentIDFromContext             = agent.SpanParentIDFromContext
	TaskIDFromContext                   = agent.TaskIDFromContext
	ToolCallIDFromContext               = agent.ToolCallIDFromContext
	TraceFromContext                    = agent.TraceFromContext
	TracingProcessorFromContext         = agent.TracingProcessorFromContext
	Truncate                            = agent.Truncate
	TruncateBytes                       = agent.TruncateBytes
	ValidSessionModeTransition          = agent.ValidSessionModeTransition
	WrapWithPolicy                      = agent.WrapWithPolicy
	WithDescription                     = agent.WithDescription
	WithHandoffs                        = agent.WithHandoffs
	WithInputFilter                     = agent.WithInputFilter
	WithInputType                       = agent.WithInputType
	WithOnHandoff                       = agent.WithOnHandoff
	WithIsEnabled                       = agent.WithIsEnabled
	WithAsToolName                      = agent.WithAsToolName
	WithAsToolDescription               = agent.WithAsToolDescription
	WithAsToolOutputExtractor           = agent.WithAsToolOutputExtractor
	WithRecommendedHandoffInstructions  = agent.WithRecommendedHandoffInstructions
	RemoveAllToolsHandoffInputFilter    = agent.RemoveAllToolsHandoffInputFilter
	WithInstructions                    = agent.WithInstructions
	WithMaxToolResultBytes              = agent.WithMaxToolResultBytes
	WithModel                           = agent.WithModel
	WithNestedRunConfig                 = agent.WithNestedRunConfig
	WithName                            = agent.WithName
	WithOutputType                      = agent.WithOutputType
	WithParentCallID                    = agent.WithParentCallID
	WithTaskID                          = agent.WithTaskID
	WithToolCallID                      = agent.WithToolCallID
	WithToolName                        = agent.WithToolName
	WithTools                           = agent.WithTools
	WithTraceContext                    = agent.WithTraceContext
	WithTracingProcessor                = agent.WithTracingProcessor
)
